#ddev-generated

type: drupal9
docroot: docroot
php_version: "8.0"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: "mysql"
  version: "5.7"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "16"

webimage_extra_packages:
  - chromium
  - chromium-driver
  - g++
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libgconf-2-4
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - make
  - python2
  - python3-pip
  - unzip
  - wget
  - xauth
  - xvfb

web_environment:
  - COMPOSER_MEMORY_LIMIT=-1
  - PHP_MEM_LIMIT=256M
  - PHP_CLI_MEM_LIMIT=512M
