#!/bin/bash

## Description: Run PHPUnit tests for the DKAN module.
## Usage: dkan-phpunit <arguments>

export XDEBUG_MODE=coverage,debug

TEST_PATH="docroot/modules/contrib/dkan"
TEST_SUITE="DKAN Test Suite"
PHPUNIT_BINARY=vendor/bin/phpunit

# Is there a PHPUnit binary?
if [[ ! -f $PHPUNIT_BINARY ]] ; then
  echo "Unable to find PHPUnit executable at $PHPUNIT_BINARY. Performing composer install."
  composer install --no-progress
fi

echo "Starting PHPUnit test run."
DDEV_PATH="$PWD"
cd $TEST_PATH || exit 1

# This command performs the actual test run.
# The test run must include the following environmental variables:
# - DRUPAL_ROOT
# - SIMPLETEST_BASE_URL
# - SIMPLETEST_DB
DRUPAL_ROOT="/var/www/html/docroot" \
  SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL \
  SIMPLETEST_DB="mysql://db:db@$DDEV_PROJECT-db:3306/db" \
  $DDEV_PATH/$PHPUNIT_BINARY \
  --testsuite "$TEST_SUITE" \
  --bootstrap /var/www/html/vendor/weitzman/drupal-test-traits/src/bootstrap.php \
  --fail-on-risky \
  "$@"
TEST_RESULTS=$?

exit $TEST_RESULTS
