#!/bin/bash
#ddev-generated

## Description: Build and run a demo site for DKAN.
## Usage: dkan-demo

# User instructions:
# ddev config --project-name=foo
# ddev composer create getdkan/recommended-project
# ddev dkan-demo
# ddev launch

# make
# TODO: how to composer create-project from within ddev?
#composer create-project getdkan/recommended-project:@stable


# install
drush site:install standard --site-name="DKAN Demo" -y
drush pm-enable dkan dkan_js_frontend config_update_ui -y
drush config-set system.performance css.preprocess 0 -y
drush config-set system.performance js.preprocess 0 -y
mkdir -p sites/default/files/uploaded_resources
mkdir -p sites/default/files/resources
chmod -R 777 sites/default/files
chmod u+w sites/default

# install sample
drush en sample_content -y
drush dkan:sample-content:create
drush queue:run datastore_import
drush dkan:metastore-search:rebuild-tracker
drush sapi-i

# frontend install
./.ddev/commands/web/dkan-frontend-install
# frontend build
./.ddev/commands/web/dkan-frontend-build

drush cr

echo "Demo site build complete. Type 'ddev launch' to visit the site."

#launch
