#!/bin/bash
#ddev-generated

## Description: Build the frontend for DKAN.
## Usage: dkan-frontend-build

FRONTEND_DOCROOT_DIR='docroot/frontend'

cd $FRONTEND_DOCROOT_DIR || exit
npm run build --force
