#!/bin/bash
#ddev-generated

## Description: Add the frontend for DKAN.
## Usage: dkan-frontend-install

FRONTEND_TMP='src/tmp'
FRONTEND_DIR='src/frontend'
FRONTEND_DOCROOT_DIR='docroot/frontend'
FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
# TODO: no-node-sass is the known-good branch, so we should move that forward to be a release.
#FRONTEND_VCS_REF='cypress-update-8.7.0'
#FRONTEND_VCS_REF='1.0.4'
FRONTEND_VCS_REF='no-node-sass'
FRONTEND_THEME='dkan_js_frontend_bartik'

# TODO: Replace this with a Composer-based dependency.

if [[ -L $FRONTEND_DOCROOT_DIR ]]; then
  echo "ERROR: Symlink $FRONTEND_DOCROOT_DIR already exists."
  exit 1
fi

#if [ -d $FRONTEND_DIR ]; then
 # echo "ERROR: Frontend $FRONTEND_DIR already exists."
  #exit 1
#fi

composer require getdkan/$FRONTEND_THEME
drush theme:enable $FRONTEND_THEME
drush config-set system.theme default $FRONTEND_THEME -y

# TODO: Glean frontend ref info from dkan module.
# cd docroot/modules/contrib/dkan
# composer config extra | jq .

mkdir -p $FRONTEND_TMP
wget -O $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip "$FRONTEND_VCS_URL"archive/$FRONTEND_VCS_REF.zip
unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d docroot/
mv docroot/data-catalog-app-$FRONTEND_VCS_REF docroot/frontend

#ln -s $PWD/$FRONTEND_DIR $FRONTEND_DOCROOT_DIR

cd $FRONTEND_DOCROOT_DIR || exit
# Don't fill the screen with warnings, only errors.
# TODO: Make sure we don't miss important warnings.
npm --loglevel=error install
