#!/bin/bash
#ddev-generated

## Description: Add the frontend for DKAN.
## Usage: dkan-frontend-install
## Flags: [{"Name":"force", "Usage":"Force installation over an existing one."}]

# User instructions:
# ddev dkan-init
# ddev dkan-site-install
# ddev dkan-frontend-install
# ddev dkan-frontend-build

# TODO: Make a CI flag.

# Fail early, fail often.
set -eu -o pipefail

FRONTEND_TMP='src/tmp'
FRONTEND_DIR='src/frontend'
FRONTEND_DOCROOT_DIR='docroot/frontend'
FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
# TODO: no-node-sass is the known-good branch, so we should move that forward to be a release.
#FRONTEND_VCS_REF='cypress-update-8.7.0'
#FRONTEND_VCS_REF='1.0.4'
FRONTEND_VCS_REF='no-node-sass'
FRONTEND_THEME='dkan_js_frontend_bartik'

# Glean flag arguments.
INSTALL_FORCE=false
while :; do
  case ${1:-} in
  --force)
    INSTALL_FORCE=true
    echo "Force install."
    ;;
  --) # End of all options.
    break
    ;;
  -?*)
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
  *) # Default case: No more options, so break out of the loop.
    break ;;
  esac
  shift
done

if [ $INSTALL_FORCE = false ]; then
  if [[ -d $FRONTEND_DOCROOT_DIR ]]; then
    echo "ERROR: $FRONTEND_DOCROOT_DIR already exists. Use --force to replace it."
    exit 1
  fi
fi

# Glean frontend spec from dkan module.
DKAN_MODULE_PATH=$(composer show --format=json getdkan/dkan | jq -r '.path')
if [ ! -z "$DKAN_MODULE_PATH" ]; then
  DKAN_MODULE_EXTRA=$(composer config extra -d $DKAN_MODULE_PATH)
  if [ ! -z "$DKAN_MODULE_EXTRA" ]; then
    DKAN_FRONTEND_CONFIG=$(jq '."dkan-fronten"' <<<$DKAN_MODULE_EXTRA)
    if [ ! -z "$DKAN_FRONTEND_CONFIG" ]; then
      FRONTEND_VCS_REF=$(jq -r --arg DEFAULT "$FRONTEND_VCS_REF" '."ref" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
      FRONTEND_VCS_URL=$(jq -r --arg DEFAULT "$FRONTEND_VCS_URL" '."url" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
    fi
  fi
fi

composer require getdkan/$FRONTEND_THEME
drush theme:enable $FRONTEND_THEME
drush config-set system.theme default $FRONTEND_THEME -y

drush pm-enable dkan_js_frontend -y

echo " ** Gathering frontend application: $FRONTEND_VCS_REF from $FRONTEND_VCS_URL"

mkdir -p $FRONTEND_TMP
wget -O $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip "$FRONTEND_VCS_URL"archive/$FRONTEND_VCS_REF.zip
unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d docroot/

if [ $INSTALL_FORCE = true ]; then
  echo " * "
  echo " * Forcing installation of frontend app over existing one."
  echo " * "
  rm -rf "$FRONTEND_DOCROOT_DIR"
fi
mv docroot/data-catalog-app-$FRONTEND_VCS_REF "$FRONTEND_DOCROOT_DIR"

cd $FRONTEND_DOCROOT_DIR || exit
# Don't fill the screen with warnings, only errors.
# TODO: Make sure we don't miss important warnings.
npm --loglevel=error install

echo " * Frontend install complete."
