#!/bin/bash
#ddev-generated

## Description: Build the frontend for DKAN.
## Usage: dkan-frontend-build

#FRONTEND_TMP='src/tmp'
#FRONTEND_DIR='src/frontend'
FRONTEND_DOCROOT_DIR='docroot/frontend'
#FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
#FRONTEND_VCS_REF='cypress-update-8.7.0'
#FRONTEND_THEME='dkan_js_frontend_bartik'

cd $FRONTEND_DOCROOT_DIR || exit
npm run build --force
