#!/bin/bash
#ddev-generated

## Description: Get environmental variables so your IDE can run PHPUnit.
## Usage: dkan-get-env-for-phpunit

echo "DRUPAL_ROOT="/var/www/html/docroot""
echo "SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL"
echo "SIMPLETEST_DB="mysql://db:db@$DDEV_PROJECT-db:3306/db""
echo "PATH=$PATH:$(which drush)"
