#!/bin/bash

#ddev-generated
## Description: (DEPRECATED - use dkan-phpunit) Run PHPUnit tests for the DKAN module.
## Usage: dkan-test-phpunit <arguments>

# Avoid some XDebug error messages.
export XDEBUG_MODE=coverage

TEST_PATH="docroot/modules/contrib/dkan"
TEST_SUITE="DKAN Test Suite"
PHPUNIT_BINARY=vendor/bin/phpunit

# Is there a PHPUnit binary?
if [[ ! -f $PHPUNIT_BINARY ]] ; then
  echo "Unable to find PHPUnit executable at $PHPUNIT_BINARY. Performing composer install."
  composer install --no-progress
fi

# Ensure prophecy.
composer require --dev phpspec/prophecy-phpunit:^2

# Add fixture users.
./.ddev/commands/web/dkan-test-users

echo "Starting PHPUnit test run."
DDEV_PATH="$PWD"
cd $TEST_PATH || exit 1

# This command performs the actual test run.
# The test run must include the following environmental variables:
# - DRUPAL_ROOT
# - SIMPLETEST_BASE_URL
# - SIMPLETEST_DB
DRUPAL_ROOT="/var/www/html/docroot" \
  SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL \
  SIMPLETEST_DB="mysql://db:db@$DDEV_PROJECT-db:3306/db" \
  $DDEV_PATH/$PHPUNIT_BINARY \
  --testsuite "$TEST_SUITE" \
  --bootstrap /var/www/html/vendor/weitzman/drupal-test-traits/src/bootstrap.php \
  --fail-on-risky \
  "$@"
TEST_RESULTS=$?

# Clean up fixture users.
cd $DDEV_PATH || exit 1
./.ddev/commands/web/dkan-test-users --remove

exit $TEST_RESULTS
