#!/bin/bash
#ddev-generated
## Description: Generate documentation for the DKAN module.
##
## Usage: dkan-docs [arguments]
## Flags: []
## Example: "ddev dkan-docs"

DOCS_PATH="modules/contrib/dkan"

cd docroot/$DOCS_PATH
doxygen "$@"

echo " * Documentation is now available at: $DDEV_PRIMARY_URL/$DOCS_PATH/docs/index.html"
