#!/bin/bash
#ddev-generated
## Description: Generate documentation for the DKAN module.
##
## Usage: dkan-docs [arguments]
## Example: "ddev dkan-docs"

$DOCS_PATH=docroot/modules/contrib/dkan

cd $DOCS_PATH
doxygen "$@"

echo " * Documentation is now available at: $DDEV_PRIMARY_URL/$DOCS_PATH"
