source "https://rubygems.org"
# gemspec

gem "jekyll", ENV["JEKYLL_VERSION"] if ENV["JEKYLL_VERSION"]
gem "kramdown-parser-gfm" if ENV["JEKYLL_VERSION"] == "~> 3.9"
gem "minima"
gem 'github-pages', group: :jekyll_plugins

gem "webrick", "~> 1.9"
